"""add_metodos_pago_table

Revision ID: b7ca4758863d
Revises: 09e4dcb6849e
Create Date: 2026-03-25 12:53:18.040312

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b7ca4758863d'
down_revision: Union[str, None] = '09e4dcb6849e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodos_pago',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nombre_titular', sa.String(length=150), nullable=False),
    sa.Column('ultimos4', sa.String(length=4), nullable=False),
    sa.Column('marca', sa.String(length=30), nullable=False),
    sa.Column('mes_expiracion', sa.Integer(), nullable=False),
    sa.Column('anio_expiracion', sa.Integer(), nullable=False),
    sa.Column('es_predeterminada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_pago_id'), 'metodos_pago', ['id'], unique=False)
    op.create_index(op.f('ix_metodos_pago_usuario_id'), 'metodos_pago', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metodos_pago_usuario_id'), table_name='metodos_pago')
    op.drop_index(op.f('ix_metodos_pago_id'), table_name='metodos_pago')
    op.drop_table('metodos_pago')
    # ### end Alembic commands ###
